#!/usr/bin/env python3
"""Regenerates lib/models/canonical_catalog.dart from hub/homehub/capabilities.py.

The direct-cloud backend has no hub to ask for `GET /capabilities`, so the app
ships a copy of the canonical registry. Run after changing capabilities.py:

    cd hub && source .venv/bin/activate && python ../app/tool/gen_canonical_catalog.py

test/canonical_catalog_test.dart fails if the copy drifts from the hub fixture.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "hub"))

from homehub.capabilities import CANONICAL  # noqa: E402


def s(v: str) -> str:
    return "'" + v.replace("\\", "\\\\").replace("'", "\\'").replace("$", "\\$") + "'"


def m(d: dict, indent: int) -> str:
    pad = " " * indent
    if not d:
        return "{}"
    rows = ",\n".join(f"{pad}  {s(k)}: {v}" for k, v in d.items())
    return "{\n" + rows + ",\n" + pad + "}"


out = ["""// GENERATED by tool/gen_canonical_catalog.py from hub/homehub/capabilities.py -- do not edit.
// A copy of the hub's canonical capability registry so the app can render
// capability-driven UI in direct-cloud mode (no hub to serve /capabilities).
import 'capability_spec.dart';

const Map<String, CapabilitySpec> canonicalCatalog = {"""]
for key, spec in CANONICAL.items():
    actions = {a: m({p: s(t) for p, t in params.items()}, 8) for a, params in spec.actions.items()}
    state = {k: s(v) for k, v in spec.state.items()}
    out.append(f"  {s(key)}: CapabilitySpec(")
    out.append(f"    key: {s(key)},")
    out.append(f"    uiHint: {s(spec.ui_hint)},")
    out.append(f"    actions: {m(actions, 4)},")
    out.append(f"    state: {m(state, 4)},")
    out.append("  ),")
out.append("};\n")
(ROOT / "app/lib/models/canonical_catalog.dart").write_text("\n".join(out))
print("wrote", len(CANONICAL), "capabilities")
